variables:
  DOCKER_BUILDKIT: 1
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  SUFFIX: ""
  PREFIX: "${CI_REGISTRY_IMAGE}/${CI_PIPELINE_ID}:"
  BUILDER_PREFIX: "registry.gitlab.cc-asp.fraunhofer.de/ipa326/docker_ros_builder/"
  BUILDER_SUFFIX: ":latest"
  ROSINSTALL_CI_JOB_TOKEN: "true"
  FOLDER: ${CI_JOB_NAME}
  ROS_DISTRO: ""
  ROS_DISTROS: noetic foxy galactic rolling humble
  ROS1_DISTROS: noetic
  ROS2_DISTROS: foxy galactic rolling humble
  NAME: ${CI_JOB_NAME}
  TARGET_LATEST: ${CI_REGISTRY_IMAGE}/${NAME}:latest
  TARGET_BRANCH: ${CI_REGISTRY_IMAGE}/${NAME}:${CI_COMMIT_REF_NAME//\//-}
  TARGET_RELEASE: ${CI_REGISTRY_IMAGE}/${NAME}:${CI_COMMIT_TAG//\//-}
  CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release"

.docker_service_tag:
  services: &docker_service
    - docker:dind
  tags: &docker_runner
      - docker-build

.simple_runner:
  tags: &simple_runner
    - asprunner

.common:
  docker_login:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - check_ros_distro
  - phoenix_dependencies
  - publish
  - cleanup
  - trigger_bridge

prepare:
  tags: *simple_runner
  stage: check_ros_distro
  script:
    - |
      for distro in $ROS_DISTROS; do
        raw=${CI_COMMIT_REF_NAME//\//-}
        if [[ "$distro" = "${raw%%-*}" ]] || [[ "$distro" = "${CI_COMMIT_REF_NAME}" ]] || [[ "$distro" = "${raw%%_*}" ]]; then
          echo "found"
          echo "ROS_DISTRO=$distro" >> build.env
          break
        fi
      done;
      if [[ $ROS_DISTRO = "" ]]; then
        exit 1
        echo "Not found"
      fi
  artifacts:
    reports:
      dotenv: build.env

.build:
  stage: ${CI_JOB_NAME}
  services: *docker_service
  tags: *docker_runner
  before_script:
    - !reference [.common, docker_login]
  script:
    - TARGET=${CI_REGISTRY_IMAGE}/${NAME}:${CI_COMMIT_REF_NAME//\//-};
    - >
      docker build
      --cache-from $TARGET
      --cache-from $TARGET_LATEST
      --cache-from $TARGET_BRANCH
      --build-arg SUFFIX
      --build-arg PREFIX
      --build-arg BUILDER_PREFIX
      --build-arg BUILDER_SUFFIX
      --build-arg ROS_DISTRO
      --build-arg ROSINSTALL_CI_JOB_TOKEN=$ROSINSTALL_CI_JOB_TOKEN
      --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN
      --build-arg BUILDKIT_INLINE_CACHE=1
      --build-arg CMAKE_ARGS
      -t ${PREFIX}${NAME}${SUFFIX} ${FOLDER}
    - docker push ${PREFIX}${NAME}${SUFFIX}
  needs:
    - prepare
  variables:
    NAME: ${CI_JOB_NAME}_${ROS_DISTRO}


phoenix_dependencies:
  extends: .build
  stage: phoenix_dependencies
  variables:
    FOLDER: .

.publish:
  stage: publish
  services: *docker_service
  tags: *docker_runner
  before_script:
    - !reference [.common, docker_login]
    - docker pull ${PREFIX}${NAME}${SUFFIX}
  script:
    - |
      TARGET=${CI_REGISTRY_IMAGE}/${NAME}:${CI_COMMIT_REF_NAME//\//-}
      if [ "$CI_COMMIT_REF_NAME" = "main" ]; then
        TARGET=$TARGET_LATEST
      fi
      if [ "$CI_COMMIT_REF_NAME" = "${ROS_DISTRO}/devel" ]; then
        TARGET=$TARGET_LATEST
      fi
      if [ $CI_COMMIT_TAG ]; then
        convert_tag=${CI_COMMIT_TAG//\//-}
        distro_prefix=${ROS_DISTRO}-
        remove_distro_tag=${convert_tag#"$distro_prefix"}
        TARGET_RELEASE=${CI_REGISTRY_IMAGE}/${NAME}:${remove_distro_tag}
        TARGET=$TARGET_RELEASE
      fi
      docker tag ${PREFIX}${NAME}${SUFFIX} ${TARGET} && docker push ${TARGET}
  needs:
    - prepare
  rules :
    - if: $CI_COMMIT_TAG != null || $CI_COMMIT_REF_NAME =~ /devel/
      when: on_success

publish:phoenix_dependencies:
  extends: .publish
  variables:
    NAME: phoenix_dependencies_${ROS_DISTRO}
  needs:
    - prepare
    - phoenix_dependencies

trigger_pipeline_in_bridge:
  tags: *simple_runner
  stage: trigger_bridge
  before_script:
    - apk add --no-cache curl
  script:
    - |
      for ros_distro in $ROS2_DISTROS; do
        if [ "$ros_distro" = "$ROS_DISTRO" ]; then
          ros_version=ros2
          break
        fi
      done
      for ros_distro in $ROS1_DISTROS; do
        if [ "$ros_distro" = "$ROS_DISTRO" ]; then
          ros_version=ros1
          break
        fi
      done
    - curl -X POST --fail -F token=$TRIGGER_BRIDGE_TOKEN -F ref=$ros_version/devel ${CI_API_V4_URL}/projects/31644/trigger/pipeline
  rules :
    - if: $CI_COMMIT_TAG != null || $CI_COMMIT_REF_NAME =~ /devel/
      when: on_success


cleanup_job:
  image: alpine:latest
  stage: cleanup
  tags: *simple_runner
  before_script:
    - apk add jq
    - apk add --no-cache curl
  script:
    - >
      curl -H "PRIVATE-TOKEN: $API_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/registry/repositories" > output.json
    - echo "CI_PIPELINE_ID=$CI_PIPELINE_ID"
    - cat output.json
    - >
      image_id=$(jq --arg CI_PIPELINE_ID "$CI_PIPELINE_ID" '.[] | select(.name==$CI_PIPELINE_ID) | .id' output.json)
    - |
      if [[ ! -z "$image_id" ]]; then
        curl --request DELETE -H "PRIVATE-TOKEN: $API_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/registry/repositories/${image_id}"
      fi
  when: always
